-- Create only: post_utme_registrations table
CREATE TABLE IF NOT EXISTS `post_utme_registrations` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT DEFAULT NULL,
  `status` VARCHAR(20) DEFAULT 'pending',

  `institution` VARCHAR(255) DEFAULT NULL,
  `first_name` VARCHAR(100) DEFAULT NULL,
  `surname` VARCHAR(100) DEFAULT NULL,
  `other_name` VARCHAR(100) DEFAULT NULL,
  `gender` VARCHAR(10) DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `parent_phone` VARCHAR(50) DEFAULT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `nin_number` VARCHAR(50) DEFAULT NULL,
  `state_of_origin` VARCHAR(100) DEFAULT NULL,
  `local_government` VARCHAR(100) DEFAULT NULL,
  `place_of_birth` VARCHAR(255) DEFAULT NULL,
  `marital_status` VARCHAR(50) DEFAULT NULL,
  `disability` TEXT DEFAULT NULL,
  `nationality` VARCHAR(100) DEFAULT NULL,
  `religion` VARCHAR(100) DEFAULT NULL,
  `mode_of_entry` VARCHAR(100) DEFAULT NULL,

  `jamb_registration_number` VARCHAR(50) DEFAULT NULL,
  `jamb_score` INT DEFAULT NULL,
  `jamb_subjects` JSON DEFAULT NULL,
  `jamb_subjects_text` TEXT DEFAULT NULL,

  `course_first_choice` VARCHAR(255) DEFAULT NULL,
  `course_second_choice` VARCHAR(255) DEFAULT NULL,
  `institution_first_choice` VARCHAR(255) DEFAULT NULL,

  `father_name` VARCHAR(255) DEFAULT NULL,
  `father_phone` VARCHAR(50) DEFAULT NULL,
  `father_email` VARCHAR(255) DEFAULT NULL,
  `father_occupation` VARCHAR(255) DEFAULT NULL,
  `mother_name` VARCHAR(255) DEFAULT NULL,
  `mother_phone` VARCHAR(50) DEFAULT NULL,
  `mother_occupation` VARCHAR(255) DEFAULT NULL,

  `sponsor_name` VARCHAR(255) DEFAULT NULL,
  `sponsor_address` VARCHAR(500) DEFAULT NULL,
  `sponsor_email` VARCHAR(255) DEFAULT NULL,
  `sponsor_phone` VARCHAR(50) DEFAULT NULL,
  `sponsor_relationship` VARCHAR(100) DEFAULT NULL,
  `next_of_kin_name` VARCHAR(255) DEFAULT NULL,
  `next_of_kin_address` VARCHAR(500) DEFAULT NULL,
  `next_of_kin_email` VARCHAR(255) DEFAULT NULL,
  `next_of_kin_phone` VARCHAR(50) DEFAULT NULL,
  `next_of_kin_relationship` VARCHAR(100) DEFAULT NULL,

  `primary_school` VARCHAR(255) DEFAULT NULL,
  `primary_year_ended` SMALLINT DEFAULT NULL,
  `secondary_school` VARCHAR(255) DEFAULT NULL,
  `secondary_year_ended` SMALLINT DEFAULT NULL,

  `exam_type` VARCHAR(20) DEFAULT NULL,
  `candidate_name` VARCHAR(255) DEFAULT NULL,
  `exam_number` VARCHAR(50) DEFAULT NULL,
  `exam_year_month` VARCHAR(20) DEFAULT NULL,
  `olevel_results` JSON DEFAULT NULL,
  `waec_token` VARCHAR(100) DEFAULT NULL,
  `waec_serial` VARCHAR(100) DEFAULT NULL,

  `passport_photo` VARCHAR(255) DEFAULT NULL,
  `payment_status` VARCHAR(20) DEFAULT 'pending',
  `form_fee_paid` TINYINT(1) DEFAULT 0,
  `tutor_fee_paid` TINYINT(1) DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  KEY `idx_user_id` (`user_id`),
  CONSTRAINT `fk_postutme_user` FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
